### ISSUE TITLE
[CodeStyle] Define Error code style

### ISSUE THREAD

**Issue by jolestar** [rooch-network/moveos#29]
Two Option:

* The first letter is E, and the rest are all capitalized, split words with `_`.
* The first letter is E, and the following words use camel case.

**Comment by pause125** [comment]
I prefer the second, as variables with all letters capitalized are more used for constants.

**Comment by geometryolife** [comment]
> I prefer the second, as variables with all letters capitalized are more used for constants.

I also prefer the second

**Comment by lshoo** [comment]
The second option is more in line with the Move code guidelines.

**Comment by jolestar** [comment]
Choose the second type.
